# Generated by Django 5.1.6 on 2025-03-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiroq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiroq',
            name='color',
            field=models.CharField(max_length=16),
        ),
    ]
