# Generated by Django 5.1.6 on 2025-03-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiroq', '0002_alter_chiroq_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiroq',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dorilar/'),
        ),
    ]
